### ISSUE TITLE
Add a new loadout type: early wave loadout

### ISSUE THREAD

**Issue by nr42111** [KFPilot/KFTurboRandomizer#2]
Wave 1-4: mix of EW/Misc/Joke loadouts
Wave 5-6: 1 scrake loadout is guaranteed the other players have a chance of getting scrake/misc/joke loadouts 
Wave 7-9: 1 FP and 1 Scrake loadouts are guaranteed, the other players have a chance of getting scrake/misc/joke loadouts
Wave 10: FP and 2 Scrake loadouts are guaranteed, other 3 players have a chance of rolling misc/joke loadouts.

**Comment by KFPilot** [comment]
Added in 0998a77eff7aa0f08633ece607fc85108c4fb06c.
