### ISSUE TITLE
Custom Weapon classes in KFTurboRandomizer cannot be switched to in inventory

### ISSUE THREAD

**Issue by nr42111** [KFPilot/KFTurboRandomizer#7]
In the regular KFTurboRandomizer gamemode, when a player is given a custom joke weapon, they cannot switch to it.

When spawning the weapon via the pickup, it works just fine.

**Comment by KFPilot** [comment]
Fixed by 0c3af9918d1347c14a8d42f1d41da479b91687c9 and 64d02d0dbdc794f65a48fe2e4f74ec3f13fda38c.
